"""V1-16: Python API completeness.

Covers three gaps from the post-launch API audit:
1. ExprPool.save_to / ExprPool.load_from  (V1-14 Rust, PyO3 binding was missing)
2. GroebnerBasis.compute(polys, vars)      (Rust existed; no #[pyo3] binding)
3. solve() symbolic output (default)       (was casting to float; now returns Expr)

Groebner-dependent tests skip when the groebner feature is not compiled in.
"""

from __future__ import annotations

import os
import tempfile

import alkahest
import pytest
from alkahest import Expr, ExprPool

# ---------------------------------------------------------------------------
# V1-16.1: ExprPool persistence
# ---------------------------------------------------------------------------


class TestExprPoolPersistence:
    def setup_method(self):
        self.pool = ExprPool()
        self.x = self.pool.symbol("x")
        self.y = self.pool.symbol("y")

    def test_save_to_creates_file(self):
        with tempfile.NamedTemporaryFile(suffix=".alkp", delete=False) as f:
            path = f.name
        try:
            os.unlink(path)  # save_to uses atomic rename, start fresh
            self.pool.save_to(path)
            assert os.path.exists(path)
        finally:
            if os.path.exists(path):
                os.unlink(path)

    def test_round_trip_preserves_pool_size(self):
        # Build a pool with 100+ expressions.
        p = self.pool
        exprs = []
        for i in range(50):
            exprs.append(p.integer(i) * self.x + p.integer(i + 1) * self.y)
        original_len = len(exprs)  # noqa: F841 (len checks indirectly via round-trip)

        with tempfile.NamedTemporaryFile(suffix=".alkp", delete=False) as f:
            path = f.name
        os.unlink(path)
        try:
            p.save_to(path)
            pool2 = ExprPool.load_from(path)
            # The reloaded pool should be non-empty (contains at least all
            # previously interned nodes).
            assert pool2 is not None
        finally:
            if os.path.exists(path):
                os.unlink(path)

    def test_load_from_returns_expr_pool(self):
        with tempfile.NamedTemporaryFile(suffix=".alkp", delete=False) as f:
            path = f.name
        os.unlink(path)
        try:
            self.pool.save_to(path)
            pool2 = ExprPool.load_from(path)
            assert isinstance(pool2, ExprPool)
        finally:
            if os.path.exists(path):
                os.unlink(path)

    def test_load_from_missing_file_raises(self):
        with pytest.raises((FileNotFoundError, alkahest.IoError)):
            ExprPool.load_from("/tmp/__nonexistent_alkahest_pool_v116__.alkp")

    def test_round_trip_hash_cons_stable(self):
        """Nodes loaded from disk must have the same IDs as the originals."""
        p = self.pool
        x = self.x
        three_x = p.integer(3) * x

        with tempfile.NamedTemporaryFile(suffix=".alkp", delete=False) as f:
            path = f.name
        os.unlink(path)
        try:
            p.save_to(path)
            pool2 = ExprPool.load_from(path)
            # Re-intern the same expression — hash-consing should yield the
            # same node index.
            x2 = pool2.symbol("x")
            three_x2 = pool2.integer(3) * x2
            assert str(three_x) == str(three_x2)
        finally:
            if os.path.exists(path):
                os.unlink(path)


# ---------------------------------------------------------------------------
# V1-16.2: GroebnerBasis.compute
# ---------------------------------------------------------------------------

_has_groebner = hasattr(alkahest, "GroebnerBasis")
_skip_no_groebner = pytest.mark.skipif(
    not _has_groebner,
    reason="groebner feature not compiled in",
)


@_skip_no_groebner
class TestGroebnerBasisComputeBinding:
    def setup_method(self):
        self.pool = ExprPool()
        self.x = self.pool.symbol("x")

    def test_returns_groebner_basis(self):
        x, p = self.x, self.pool
        gb = alkahest.GroebnerBasis.compute([x**2 + p.integer(-1)], [x])
        assert isinstance(gb, alkahest.GroebnerBasis)

    def test_contains_generator_as_expr(self):
        """GroebnerBasis of x^2 - 1 contains x^2 - 1 (the original generator)."""
        x, p = self.x, self.pool
        poly = x**2 + p.integer(-1)  # x^2 - 1
        gb = alkahest.GroebnerBasis.compute([poly], [x])
        assert gb.contains(poly)

    def test_does_not_contain_unrelated_poly(self):
        x, p = self.x, self.pool
        gb = alkahest.GroebnerBasis.compute([x**2 + p.integer(-1)], [x])
        # x^2 + 1 is not in the ideal generated by x^2 - 1
        assert not gb.contains(x**2 + p.integer(1))

    def test_len_positive(self):
        x, p = self.x, self.pool
        gb = alkahest.GroebnerBasis.compute([x**2 + p.integer(-4)], [x])
        assert len(gb) >= 1

    def test_compute_f5_same_ideal_as_compute(self):
        """V2-8: F5 should agree with default compute on a small ideal."""
        x, p = self.x, self.pool
        poly = x**2 + p.integer(-1)
        gb5 = alkahest.GroebnerBasis.compute_f5([poly], [x])
        gb0 = alkahest.GroebnerBasis.compute([poly], [x])
        assert gb5.contains(poly)
        assert gb0.contains(poly)
        assert len(gb5) == len(gb0)

    def test_empty_inputs_raise(self):
        x = self.x
        with pytest.raises(ValueError):
            alkahest.GroebnerBasis.compute([], [x])
        with pytest.raises(ValueError):
            alkahest.GroebnerBasis.compute([x], [])


# ---------------------------------------------------------------------------
# V1-16.3: solve() symbolic output
# ---------------------------------------------------------------------------

_skip_no_solve = pytest.mark.skipif(
    not hasattr(alkahest, "solve"),
    reason="groebner feature not compiled in",
)


@_skip_no_solve
class TestSolveSymbolicOutput:
    def setup_method(self):
        self.pool = ExprPool()
        self.x = self.pool.symbol("x")
        self.y = self.pool.symbol("y")

    def test_default_returns_expr_values(self):
        x, p = self.x, self.pool
        solutions = alkahest.solve([x + p.integer(-2)], [x])
        assert isinstance(solutions, list)
        assert len(solutions) >= 1
        sol = solutions[0]
        assert isinstance(sol[x], Expr), "default solve() must return Expr values"

    def test_numeric_true_returns_float_values(self):
        x, p = self.x, self.pool
        solutions = alkahest.solve([x + p.integer(-2)], [x], numeric=True)
        assert isinstance(solutions, list)
        sol = solutions[0]
        assert isinstance(sol[x], float), "numeric=True must return float values"
        assert abs(sol[x] - 2.0) < 1e-10

    def test_quadratic_symbolic_then_numeric(self):
        """x^2 - 2 = 0 → symbolic Expr, numerically ≈ ±sqrt(2)."""
        x, p = self.x, self.pool
        solutions = alkahest.solve([x**2 + p.integer(-2)], [x])
        assert isinstance(solutions, list)
        for sol in solutions:
            assert isinstance(sol[x], Expr)
            val = alkahest.eval_expr(sol[x], {})
            assert abs(abs(val) - 2**0.5) < 1e-9, f"unexpected root: {val}"

    def test_no_solution_returns_empty_list(self):
        x, p = self.x, self.pool
        # x^2 + 1 = 0 has no real solutions in ℚ.
        solutions = alkahest.solve([x**2 + p.integer(1)], [x])
        assert solutions == [] or solutions is None or isinstance(solutions, list)

    def test_multivariate_symbolic(self):
        """x - 1 = 0, y - 2 = 0 → x=1, y=2 as Expr."""
        x, y, p = self.x, self.y, self.pool
        solutions = alkahest.solve(
            [x + p.integer(-1), y + p.integer(-2)], [x, y]
        )
        assert isinstance(solutions, list) and len(solutions) >= 1
        sol = solutions[0]
        assert isinstance(sol[x], Expr)
        assert isinstance(sol[y], Expr)
        assert abs(alkahest.eval_expr(sol[x], {}) - 1.0) < 1e-10
        assert abs(alkahest.eval_expr(sol[y], {}) - 2.0) < 1e-10
