"""Certificate ledger — a queryable, auditable map of where Lean certification stops.

:attr:`alkahest.DerivedResult.certificate` returns Lean 4 source *sometimes*.
The withhold-rather-than-lie discipline behind that is enforced by an
emit-then-typecheck CI gate (``.github/workflows/lean.yml``), but it leaves a
planning problem: an agent choosing between a fast route and a certifiable one
has no way to know, before spending the compute, which is which.

This module closes that gap with three pieces:

``certifiable(op, *args)``
    A predicate that answers "will this call yield a certificate?" — with a
    *reason* when the answer is no, not a bare ``False``.

:func:`certificate_coverage`
    The per-operation coverage table, **generated by running a corpus** rather
    than hand-maintained (see ``scripts/gen_certificate_ledger.py``), checked
    into the repo as ``certificate_ledger.json``, and pinned by a CI drift
    check. Hand-maintained capability bits are how ``lean_theorem: true`` once
    got advertised for primitives the emitter could not prove; a table that is
    only ever *observed* cannot drift that way without CI noticing.

:func:`require_certificate`
    Fail loudly instead of silently degrading, per call or ambiently via
    ``with alkahest.context(require_certificate=True)``.

Shape classes
-------------
The ledger is keyed by *shape class*: an operation plus a small vector of
structural features of its arguments (which primitive functions occur, whether
they are applied to the bare variable or to a composite, what kind of exponents
appear, and so on). Shape classes are deliberately coarse enough to generalise
to expressions the corpus never saw, and — as the generator verifies — fine
enough that no observed class mixes certified and withheld outcomes.

A class earns the ``certified`` verdict only if *every* corpus observation in it
emitted a certificate. Anything else (``withheld``, ``conditional``,
``partial``, or a class the corpus never reached) makes :func:`certifiable`
answer ``False``. The predicate under-claims by construction.
"""

from __future__ import annotations

import json
import os
from typing import Any

__all__ = [
    "Certifiability",
    "certifiable",
    "certificate_coverage",
    "require_certificate",
]

_LEDGER_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "certificate_ledger.json")

#: Bumped when the shape-class feature vector or the ledger file layout changes.
#: The generator stamps it into the artifact and :func:`_ledger` refuses a file
#: written by an incompatible generator.
SCHEMA_VERSION = 1

# ---------------------------------------------------------------------------
# Operation signatures
#
# Which positional argument carries the expression, which (if any) carries the
# distinguished variable, and whether trailing bounds make the call "definite".
# This is a table of *signatures*, not of outcomes — outcomes are only ever
# observed by running the corpus.
# ---------------------------------------------------------------------------

OPERATIONS: dict[str, dict[str, Any]] = {
    "diff": {"var": 1, "bounds": None},
    "integrate": {"var": 1, "bounds": 2},
    "simplify": {"var": None, "bounds": None},
    "simplify_trig": {"var": None, "bounds": None},
    "simplify_trig_normal_form": {"var": None, "bounds": None},
    "simplify_log_exp": {"var": None, "bounds": None},
    "simplify_egraph": {"var": None, "bounds": None},
    "simplify_expanded": {"var": None, "bounds": None},
    "sum_indefinite": {"var": 1, "bounds": None},
    "sum_definite": {"var": 1, "bounds": 2},
    "product_indefinite": {"var": 1, "bounds": None},
    "product_definite": {"var": 1, "bounds": 2},
}

#: Feature names in the fixed order used to build a shape-class key.
FEATURES = ("form", "funcs", "fn_arg", "mul", "pow", "pow_base", "definite")

_NUMERIC_TAGS = ("integer", "rational", "float")

_TOP_FORM = {
    "symbol": "atom",
    "integer": "atom",
    "rational": "atom",
    "float": "atom",
    "func": "apply",
    "add": "sum",
    "mul": "product",
    "pow": "power",
}

# Ordered from "most certifiable" to "least", so a feature can be summarised
# over a whole expression by keeping the worst case.
_FN_ARG_RANK = {"none": 0, "var": 1, "pow": 2, "other": 3}
_POW_RANK = {"none": 0, "nat": 1, "neg": 2, "frac": 3, "sym": 4}
_MUL_RANK = {"none": 0, "scalar": 1, "general": 2}


# ---------------------------------------------------------------------------
# Shape classification
# ---------------------------------------------------------------------------


def _walk(expr):
    """Yield *expr* and every subexpression, depth-first."""
    yield expr
    node = expr.node()
    tag = node[0]
    if tag == "func":
        for arg in node[2]:
            yield from _walk(arg)
    elif tag in ("add", "mul"):
        for arg in node[1]:
            yield from _walk(arg)
    elif tag == "pow":
        yield from _walk(node[1])
        yield from _walk(node[2])


def _is_var(expr, var) -> bool:
    return var is not None and str(expr) == str(var)


def _is_int_pow_of_var(expr, var) -> bool:
    node = expr.node()
    return node[0] == "pow" and _is_var(node[1], var) and node[2].node()[0] == "integer"


def canonical_expression(expr) -> str:
    """Render *expr* with commutative operands in a fixed order.

    ``str(expr)`` is *not* reproducible across processes: the kernel's ordering
    of ``add``/``mul`` operands depends on a randomly-seeded hash, so the same
    sum can print with its terms swapped from one run to the next. That is
    harmless for a human reading one result, but it would make the ledger's
    example column — and therefore the byte-for-byte CI drift check — a coin
    flip. Sorting commutative operands by their own rendering makes the example
    a stable property of the expression rather than of the run that produced it.
    """
    node = expr.node()
    tag = node[0]
    if tag in ("symbol", "integer", "float"):
        return str(node[1])
    if tag == "rational":
        return f"{node[1]}/{node[2]}"
    if tag == "func":
        return f"{node[1]}({', '.join(canonical_expression(a) for a in node[2])})"
    if tag in ("add", "mul"):
        operands = sorted(canonical_expression(a) for a in node[1])
        separator = " + " if tag == "add" else " * "
        return "(" + separator.join(operands) + ")"
    if tag == "pow":
        return f"{_atom_or_parens(node[1])}^{_atom_or_parens(node[2])}"
    return f"<{tag}>"


def _atom_or_parens(expr) -> str:
    """Render *expr*, parenthesised unless it is a bare symbol or integer.

    Keeps nested powers unambiguous: ``(x^(1/2))^3`` rather than ``x^1/2^3``.
    """
    rendered = canonical_expression(expr)
    if expr.node()[0] in ("symbol", "integer"):
        return rendered
    if rendered.startswith("(") and rendered.endswith(")"):
        return rendered
    return f"({rendered})"


def shape_features(expr, var=None, definite: bool | None = None) -> dict[str, str]:
    """Structural feature vector for one call, used as the ledger key.

    The features are chosen to track the seams the Lean emitter actually has:
    which primitives are involved, whether they are applied pointwise to the
    variable (the fragment ``Real.deriv_*`` covers) or to a composite argument
    (which needs ``HasDerivAt.comp``), whether any exponent is negative or
    fractional (which introduces the ``x ≠ 0`` side conditions the combine
    tactic does not yet thread through), and how the pieces are combined.
    """
    funcs: set[str] = set()
    fn_arg = "none"
    pow_kind = "none"
    pow_base = "none"
    mul_kind = "none"

    for sub in _walk(expr):
        node = sub.node()
        tag = node[0]
        if tag == "func":
            funcs.add(node[1])
            for arg in node[2]:
                if _is_var(arg, var):
                    kind = "var"
                elif _is_int_pow_of_var(arg, var):
                    kind = "pow"
                else:
                    kind = "other"
                if _FN_ARG_RANK[kind] > _FN_ARG_RANK[fn_arg]:
                    fn_arg = kind
        elif tag == "pow":
            exponent = node[2].node()
            if exponent[0] == "integer":
                kind = "nat" if int(exponent[1]) >= 0 else "neg"
            elif exponent[0] in ("rational", "float"):
                kind = "frac"
            else:
                kind = "sym"
            if _POW_RANK[kind] > _POW_RANK[pow_kind]:
                pow_kind = kind
            base = "var" if _is_var(node[1], var) else "expr"
            if pow_base == "none" or base == "expr":
                pow_base = base
        elif tag == "mul":
            non_numeric = [a for a in node[1] if a.node()[0] not in _NUMERIC_TAGS]
            kind = "scalar" if len(non_numeric) <= 1 else "general"
            if _MUL_RANK[kind] > _MUL_RANK[mul_kind]:
                mul_kind = kind

    features = {
        "form": _TOP_FORM.get(expr.node()[0], "other"),
        "funcs": ",".join(sorted(funcs)) or "-",
        "fn_arg": fn_arg,
        "mul": mul_kind,
        "pow": pow_kind,
    }
    # `pow_base` is only meaningful relative to a distinguished variable, and
    # `definite` only for operations that take bounds. Omitting them elsewhere
    # keeps the table free of constant-valued columns.
    if var is not None:
        features["pow_base"] = pow_base
    if definite is not None:
        features["definite"] = "yes" if definite else "no"
    return features


def shape_class(op: str, features: dict[str, str]) -> str:
    """Render *features* as the stable ledger key for *op*."""
    parts = [f"{name}={features[name]}" for name in FEATURES if name in features]
    return "/".join([op, *parts])


def classify(op: str, args, kwargs=None) -> tuple[str, dict[str, str]]:
    """Return ``(shape_class, features)`` for a prospective ``op(*args)`` call.

    Raises
    ------
    ValueError
        If *op* is not a ledger-tracked operation, or the arguments do not
        match its signature.
    """
    from . import DerivedResult, Expr  # local import: avoids a package cycle

    spec = OPERATIONS.get(op)
    if spec is None:
        raise ValueError(
            f"certifiable: unknown operation {op!r}. "
            f"Tracked operations: {', '.join(sorted(OPERATIONS))}"
        )
    kwargs = kwargs or {}
    if not args:
        raise ValueError(f"certifiable: {op} requires at least an expression argument")

    expr = args[0]
    if isinstance(expr, DerivedResult):
        expr = expr.value
    if not isinstance(expr, Expr):
        raise ValueError(f"certifiable: {op} expects an Expr as its first argument")

    var = None
    if spec["var"] is not None and len(args) > spec["var"]:
        candidate = args[spec["var"]]
        if isinstance(candidate, Expr):
            var = candidate

    definite = None
    if spec["bounds"] is not None:
        if len(args) > spec["bounds"]:
            lower = args[spec["bounds"]]
        else:
            # `integrate` names its bounds `a`/`b`; the sum/product family uses
            # `lo`/`hi`. Either may be passed by keyword.
            lower = kwargs.get("a", kwargs.get("lo"))
        definite = lower is not None

    features = shape_features(expr, var, definite)
    return shape_class(op, features), features


# ---------------------------------------------------------------------------
# The checked-in ledger
# ---------------------------------------------------------------------------

_LEDGER_CACHE: dict[str, Any] | None = None


def _ledger() -> dict[str, Any]:
    """Load (and memoise) the generated ledger artifact."""
    global _LEDGER_CACHE
    if _LEDGER_CACHE is None:
        data: dict[str, Any]
        try:
            with open(_LEDGER_PATH, encoding="utf-8") as handle:
                data = json.load(handle)
        except FileNotFoundError:  # pragma: no cover — packaging failure
            data = {"schema_version": SCHEMA_VERSION, "rows": [], "corpus": {}}
        if data.get("schema_version") != SCHEMA_VERSION:  # pragma: no cover
            raise RuntimeError(
                f"certificate_ledger.json has schema_version "
                f"{data.get('schema_version')!r}, expected {SCHEMA_VERSION}. "
                "Regenerate with `python scripts/gen_certificate_ledger.py`."
            )
        data["_index"] = {row["shape"]: row for row in data.get("rows", [])}
        _LEDGER_CACHE = data
    return _LEDGER_CACHE


def certificate_coverage(operation: str | None = None) -> list[dict[str, Any]]:
    """Return the generated per-operation certificate coverage table.

    Each row describes one shape class::

        {
          "operation":    "integrate",
          "shape":        "integrate/form=apply/funcs=log/...",
          "features":     {"form": "apply", "funcs": "log", ...},
          "verdict":      "withheld",
          "observations": {"certified": 0, "withheld": 3, "no_derivation": 0},
          "examples":     ["log(x)", ...],
        }

    ``verdict`` is one of:

    ``certified``
        Every corpus observation of this shape emitted a certificate.
        :func:`certifiable` answers ``True`` here and nowhere else.
    ``withheld``
        No observation emitted; the emitter cannot prove this shape today.
    ``conditional``
        Emits when the operation actually rewrites something, but some
        observations had an empty derivation log (nothing to prove). Not
        predictable from the arguments alone, so :func:`certifiable` answers
        ``False`` with reason ``"class_conditional"``.
    ``partial``
        Mixed certified and withheld observations — the shape class is too
        coarse to separate them. The generator reports these; a healthy tree
        has none.

    Parameters
    ----------
    operation : str, optional
        Restrict to one operation (e.g. ``"diff"``).

    Returns
    -------
    list of dict
        Sorted by ``operation`` then ``shape``.

    Example
    -------
    >>> import alkahest as ak
    >>> withheld = [r for r in ak.certificate_coverage("integrate")
    ...             if r["verdict"] == "withheld"]
    """
    rows = _ledger().get("rows", [])
    if operation is not None:
        rows = [row for row in rows if row["operation"] == operation]
    return [dict(row) for row in rows]


def coverage_summary() -> dict[str, Any]:
    """Aggregate counts over :func:`certificate_coverage`, for ``capabilities()``."""
    ledger = _ledger()
    verdicts: dict[str, int] = {}
    operations: dict[str, dict[str, int]] = {}
    for row in ledger.get("rows", []):
        verdicts[row["verdict"]] = verdicts.get(row["verdict"], 0) + 1
        per_op = operations.setdefault(row["operation"], {})
        per_op[row["verdict"]] = per_op.get(row["verdict"], 0) + 1
    return {
        "schema_version": ledger.get("schema_version"),
        "generated_from": ledger.get("corpus", {}),
        "shape_classes": verdicts,
        "operations": operations,
    }


def certifiable_primitives() -> set[str]:
    """Primitive names whose pointwise derivative ``d/dx f(x)`` certifies.

    Derived from the ledger, so ``capabilities()["primitives"][i]["lean_theorem"]``
    and the coverage table cannot disagree.
    """
    names: set[str] = set()
    for row in _ledger().get("rows", []):
        if row["operation"] != "diff" or row["verdict"] != "certified":
            continue
        features = row["features"]
        if (
            features.get("form") == "apply"
            and features.get("fn_arg") == "var"
            and features.get("pow") == "none"
            and "," not in features.get("funcs", ",")
            and features.get("funcs") != "-"
        ):
            names.add(features["funcs"])
    return names


# ---------------------------------------------------------------------------
# The predicate
# ---------------------------------------------------------------------------


class Certifiability:
    """The answer to "will this call yield a Lean certificate?".

    Truthy exactly when a certificate is (or would be) produced, so it drops
    into ``if certifiable(...):`` — but it carries the *reason*, which is what
    a planning loop actually needs.

    Attributes
    ----------
    certifiable : bool
        The verdict. ``bool(self)`` is the same value.
    operation : str
        The operation asked about.
    shape : str
        Shape-class key (see :func:`certificate_coverage`).
    verdict : str
        Ledger verdict for the shape class: ``"certified"``, ``"withheld"``,
        ``"conditional"``, ``"partial"``, or ``"unknown"`` (never observed).
    reason : str
        Stable reason code. ``"emitted"`` / ``"withheld_no_derivation"`` /
        ``"withheld_uncertifiable_step"`` / ``"withheld_integration_shape"``
        come from actually running the operation; ``"class_certified"`` /
        ``"class_withheld"`` / ``"class_conditional"`` / ``"class_partial"`` /
        ``"unknown_shape"`` come from the ledger alone; ``"operation_failed"``
        means the operation itself raised.
    detail : str
        One-sentence human explanation.
    checked : bool
        ``True`` when the operation was actually run, so the verdict is exact
        rather than predicted.
    result : DerivedResult or None
        The result computed while checking — returned so a caller that goes on
        to use it does not pay for the computation twice.
    error : Exception or None
        The exception raised by the operation, if any.
    evidence : dict or None
        The ledger row backing this answer.
    """

    __slots__ = (
        "certifiable",
        "checked",
        "detail",
        "error",
        "evidence",
        "operation",
        "reason",
        "result",
        "shape",
        "verdict",
    )

    def __init__(
        self,
        *,
        certifiable: bool,
        operation: str,
        shape: str,
        verdict: str,
        reason: str,
        detail: str,
        checked: bool = False,
        result: Any = None,
        error: Exception | None = None,
        evidence: dict[str, Any] | None = None,
    ) -> None:
        self.certifiable = certifiable
        self.operation = operation
        self.shape = shape
        self.verdict = verdict
        self.reason = reason
        self.detail = detail
        self.checked = checked
        self.result = result
        self.error = error
        self.evidence = evidence

    def __bool__(self) -> bool:
        return self.certifiable

    def __repr__(self) -> str:
        return (
            f"Certifiability({self.certifiable}, operation={self.operation!r}, "
            f"reason={self.reason!r}, checked={self.checked})"
        )

    def as_dict(self) -> dict[str, Any]:
        """JSON-serialisable view (omits ``result``, which is not serialisable)."""
        return {
            "certifiable": self.certifiable,
            "operation": self.operation,
            "shape": self.shape,
            "verdict": self.verdict,
            "reason": self.reason,
            "detail": self.detail,
            "checked": self.checked,
            "evidence": self.evidence,
        }


_LEDGER_REASON = {
    "certified": ("class_certified", "every corpus observation of this shape certified"),
    "withheld": ("class_withheld", "no corpus observation of this shape ever certified"),
    "conditional": (
        "class_conditional",
        "this shape certifies only when the operation actually rewrites something; "
        "run it to find out",
    ),
    "partial": (
        "class_partial",
        "corpus observations of this shape disagree, so the answer cannot be predicted",
    ),
}


def certifiable(op, *args, mode: str = "verify", **kwargs) -> Certifiability:
    """Will running *op* on these arguments produce a Lean certificate?

    Parameters
    ----------
    op : str or callable
        Operation name (``"integrate"``) or the function itself
        (``alkahest.integrate``). See :data:`OPERATIONS` for the tracked set.
    *args, **kwargs
        The arguments you would pass to *op*.
    mode : {"verify", "ledger"}
        ``"verify"`` (default) is **sound**: it never answers ``True`` without a
        certificate in hand. It short-circuits to ``False`` for shape classes
        the ledger records as never certifying, and otherwise runs *op* and
        inspects the result — which it hands back on
        :attr:`Certifiability.result`, so the work is not wasted.

        ``"ledger"`` runs nothing at all and answers from the checked-in
        coverage table. Use it for planning across many candidate routes where
        even one evaluation each is too much. Its ``True`` is an empirical
        claim about the shape class, validated against the corpus in CI, not a
        certificate in hand.

    Returns
    -------
    Certifiability
        Truthy iff a certificate is (or would be) produced; carries the reason.

    Examples
    --------
    >>> import alkahest as ak
    >>> p = ak.ExprPool(); x = p.symbol("x")
    >>> bool(ak.certifiable("diff", ak.sin(x), x))
    True
    >>> answer = ak.certifiable("integrate", ak.log(x), x)
    >>> bool(answer), answer.reason
    (False, 'class_withheld')

    Plan a route without computing anything::

        routes = [("integrate", f, x), ("diff", F, x)]
        best = max(routes, key=lambda r: bool(ak.certifiable(*r, mode="ledger")))
    """
    if mode not in ("verify", "ledger"):
        raise ValueError(f"certifiable: mode must be 'verify' or 'ledger', got {mode!r}")

    name = op if isinstance(op, str) else getattr(op, "__name__", None)
    if not isinstance(name, str):
        raise ValueError("certifiable: op must be an operation name or an alkahest function")

    shape, _features = classify(name, args, kwargs)
    row = _ledger()["_index"].get(shape)
    verdict = row["verdict"] if row else "unknown"
    reason, detail = _LEDGER_REASON.get(
        verdict,
        ("unknown_shape", "no corpus observation of this shape class"),
    )

    if mode == "ledger":
        return Certifiability(
            certifiable=verdict == "certified",
            operation=name,
            shape=shape,
            verdict=verdict,
            reason=reason,
            detail=detail,
            evidence=row,
        )

    # Sound mode. A `withheld` class is the one prediction worth trusting
    # without paying for it: answering False costs the caller a certifiable
    # route at worst, and the whole point of the predicate is to under-claim.
    if verdict == "withheld":
        return Certifiability(
            certifiable=False,
            operation=name,
            shape=shape,
            verdict=verdict,
            reason=reason,
            detail=detail,
            evidence=row,
        )

    from . import _context

    try:
        # Suppress an ambient `require_certificate`: asking whether something
        # certifies must never itself raise for the answer being "no". The
        # overlay keeps the caller's pool/domain/assumptions, so the probe runs
        # under exactly the conditions the real call would.
        with _context._overlay(require_certificate=False):
            import alkahest

            result = getattr(alkahest, name)(*args, **kwargs)
    except Exception as exc:
        return Certifiability(
            certifiable=False,
            operation=name,
            shape=shape,
            verdict=verdict,
            reason="operation_failed",
            detail=f"{type(exc).__name__}: {exc}",
            checked=True,
            error=exc,
            evidence=row,
        )

    status = result.certificate_status
    emitted = status["certifiable"]
    if emitted:
        explanation = "certificate emitted"
    elif status["blocking_steps"]:
        blocking = ", ".join(sorted({step["rule"] for step in status["blocking_steps"]}))
        explanation = f"no sound Lean encoding for rewrite rule(s): {blocking}"
    elif status["reason"] == "withheld_no_derivation":
        explanation = "derivation log is empty — nothing to certify"
    else:
        explanation = "the emitter withheld the certificate for this shape"

    return Certifiability(
        certifiable=emitted,
        operation=name,
        shape=shape,
        verdict=verdict,
        reason=status["reason"],
        detail=explanation,
        checked=True,
        result=result,
        evidence=row,
    )


# ---------------------------------------------------------------------------
# require_certificate
# ---------------------------------------------------------------------------


def require_certificate(result):
    """Return *result* if it carries a Lean certificate; otherwise raise.

    The per-call form of the ambient
    ``with alkahest.context(require_certificate=True)`` mode. Use it to turn a
    silent degradation — a result that quietly arrives without evidence — into
    a loud, coded failure at the point it happens.

    Parameters
    ----------
    result : DerivedResult
        The result to check. Returned unchanged when it certifies, so this
        wraps a call inline.

    Returns
    -------
    DerivedResult

    Raises
    ------
    CertificateUnavailableError
        ``E-CERT-001``, carrying the withholding reason and any blocking
        rewrite rules in its remediation text.

    Example
    -------
    >>> import alkahest as ak
    >>> p = ak.ExprPool(); x = p.symbol("x")
    >>> ak.require_certificate(ak.diff(ak.sin(x), x)).value
    cos(x)

    Ambient form, for a loop that must not produce uncertified claims::

        with ak.context(require_certificate=True):
            claim = ak.integrate(f, x)   # raises E-CERT-001 rather than
                                         # returning an uncertified result
    """
    from . import DerivedResult
    from .exceptions import CertificateUnavailableError

    if not isinstance(result, DerivedResult):
        raise TypeError(f"require_certificate expects a DerivedResult, got {type(result).__name__}")
    if result.certificate is not None:
        return result

    status = result.certificate_status
    blocking = sorted({step["rule"] for step in status["blocking_steps"]})
    if blocking:
        remediation = (
            "No sound Lean encoding exists for rewrite rule(s) "
            f"{', '.join(blocking)}. Use alkahest.certificate_coverage() to find a "
            "certifiable route, or drop the require_certificate requirement."
        )
    elif status["reason"] == "withheld_no_derivation":
        remediation = (
            "The derivation log is empty — the operation changed nothing, so there is "
            "no theorem to certify."
        )
    else:
        remediation = (
            "This shape is outside the certifiable fragment. Use "
            "alkahest.certificate_coverage() to see which shapes certify."
        )
    raise CertificateUnavailableError(
        f"no Lean certificate available for this result ({status['reason']})",
        remediation=remediation,
    )


def certificate_required() -> bool:
    """Return ``True`` when ``context(require_certificate=True)`` is active."""
    from ._context import get_context_value

    return bool(get_context_value("require_certificate", False))
